"use client";

import { useCallback, useEffect, useState } from "react";
import { Loader2, RefreshCw, Sparkles } from "lucide-react";
import { api, PRIORITY_META } from "@/lib/client";
import type { LifePlanDTO } from "@/shared/types";
import { StateCard } from "../dashboard/parts";
import { EmptyPlan, PlanSection, StepItem } from "./plan-parts";

export default function PlanPage() {
  const [plan, setPlan] = useState<LifePlanDTO | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    try {
      const data = await api<{ plan: LifePlanDTO | null }>("/api/plan");
      setPlan(data.plan);
      setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not load plan");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void load();
  }, [load]);

  async function generate() {
    setGenerating(true);
    try {
      const data = await api<{ plan: LifePlanDTO }>("/api/plan/generate", {
        body: { reason: "manual" },
      });
      setPlan(data.plan);
    } catch (err) {
      alert(err instanceof Error ? err.message : "Generation failed");
    } finally {
      setGenerating(false);
    }
  }

  if (loading)
    return (
      <div className="animate-pulse space-y-4 pt-2">
        {[...Array(5)].map((_, i) => (
          <div key={i} className="h-20 rounded-xl bg-secondary" />
        ))}
      </div>
    );
  if (error) return <StateCard title="Something went wrong" message={error} retry={load} />;
  if (!plan) return <EmptyPlan generating={generating} onGenerate={() => void generate()} />;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-xl font-bold">Your relocation plan</h1>
        <button
          type="button"
          onClick={() => void generate()}
          disabled={generating}
          className="inline-flex items-center gap-1.5 rounded-full border border-primary/40 bg-primary/5 px-3 py-1.5 text-xs font-semibold text-primary disabled:opacity-50"
        >
          {generating ? (
            <Loader2 className="h-3 w-3 animate-spin" />
          ) : (
            <RefreshCw className="h-3 w-3" />
          )}
          Regenerate
        </button>
      </div>

      <section className="rounded-xl bg-primary p-4 text-primary-foreground shadow-lg shadow-primary/15">
        <p className="flex items-center gap-1.5 text-xs font-medium uppercase tracking-wide opacity-80">
          <Sparkles className="h-3.5 w-3.5" />
          Summary · v{plan.version}
        </p>
        <p className="mt-2 text-sm leading-relaxed">{plan.summary}</p>
        <p className="mt-2 text-[11px] opacity-60">generated by: {plan.generatedBy}</p>
      </section>

      <PlanSection title="Top priorities">
        <ul className="space-y-2">
          {plan.priorities.map((p, i) => (
            <li key={i} className="rounded-xl border border-border bg-card p-3.5 shadow-sm">
              <div className="flex items-start justify-between gap-3">
                <p className="text-sm font-semibold">
                  {PRIORITY_META[p.priority]?.emoji} {p.title}
                </p>
                <span
                  className={`shrink-0 text-[10px] font-bold uppercase ${PRIORITY_META[p.priority]?.className}`}
                >
                  {p.priority}
                </span>
              </div>
              <p className="mt-1 text-xs leading-relaxed text-muted-foreground">{p.reason}</p>
            </li>
          ))}
        </ul>
      </PlanSection>

      <PlanSection title="First 24 hours">
        <ol className="space-y-2">
          {plan.first24Hours.map((t, i) => (
            <StepItem key={i} index={i + 1} text={t} />
          ))}
        </ol>
      </PlanSection>

      <PlanSection title="First 7 days">
        <div className="space-y-2.5">
          {plan.first7Days.map((d) => (
            <div
              key={d.day}
              className="flex gap-3 rounded-xl border border-border bg-card p-3.5 shadow-sm"
            >
              <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-primary/10 text-xs font-bold text-primary">
                {d.day}
              </span>
              <ul className="min-w-0 flex-1 space-y-1">
                {d.tasks.map((t, i) => (
                  <li key={i} className="text-sm leading-snug">
                    {t}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </PlanSection>

      <PlanSection title="Ongoing settling">
        <ul className="space-y-2">
          {plan.ongoing.map((t, i) => (
            <li key={i} className="flex items-start gap-2 rounded-xl bg-secondary/50 px-3.5 py-2.5">
              <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-accent" />
              <span className="text-sm leading-snug">{t}</span>
            </li>
          ))}
        </ul>
      </PlanSection>

      <p className="pb-2 text-center text-[11px] leading-relaxed text-muted-foreground">
        Your plan regenerates automatically when your arrival date or housing status changes.
      </p>
    </div>
  );
}
